project:
  type: website
  output-dir: docs

website:
  favicon: ./logos/Mikey_He.png
  navbar:
    title: false
    logo: ./logos/Mikey_He.png
    logo-alt: "Logo"
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: Photography.qmd
        text: Photography
      - Experience.qmd

format:
  html:
    theme: 
      - minty
      - styles.scss
    mainfont: Nunito
    css: styles.css
    toc: true

editor: visual

